EHS_MVC/Controllers/BuyersController.cs
using EHS_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace EHS_MVC.Controllers
{

    public class BuyersController : Controller
    {
        public string SelectedValue { get; set; }
        public string PriceRange { get; set; }
        public string PropertyOption { get; set; }

        private readonly IConfiguration _configuration;
        public BuyersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string propertyOption,[FromQuery] string selectedValue, [FromQuery] string priceRange = "-1")
        {
            SelectedValue = selectedValue;
            PriceRange= priceRange;
            PropertyOption = propertyOption;
            PropertyViewModel propertyViewModel = new();
            List<SellerHouseDetailsViewModel> houses = new();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);

                if (string.IsNullOrEmpty(selectedValue))
                {
                    selectedValue = "All";
                    propertyOption = "null";
                   
                }
               


                var result = await client.GetAsync($"Buyers/GetHouseByType/{selectedValue}");
                var tempimages = await client.GetAsync("HouseImages/GetAllHouseImages");

                decimal priceInt = Convert.ToDecimal(priceRange); //Convert.ToInt32(priceRange);
                if (result.IsSuccessStatusCode)
                {
                    var allImages = await tempimages.Content.ReadAsAsync<List<HouseImage>>();
                    propertyViewModel.HouseImages = allImages;

                    houses = await result.Content.ReadAsAsync<List<SellerHouseDetailsViewModel>>();
                    if (priceInt > 0 && priceInt <30000 )
                    {
                        if (priceInt == 1)
                            priceInt = 0;
                        houses = houses.FindAll(h => h.PriceRange >= priceInt && h.PriceRange < priceInt + 10000);
                        
                    }
                    if(priceInt == 30000)
                    {
                        houses = houses.FindAll(h => h.PriceRange >= priceInt);

                    }
                    if(propertyOption != "null")
                    {
                        houses = houses.FindAll(h => h.PropertyOption == propertyOption);
                    }
                }
                else
                {
                    houses = new List<SellerHouseDetailsViewModel>();

                }





                propertyViewModel.HouseViewModels = houses;
                propertyViewModel.Values = new List<SelectListItem>
                        {
                            new SelectListItem { Value = "All", Text = "All" },
                            new SelectListItem { Value = "Villa", Text = "Villa" },
                            new SelectListItem { Value = "Flat", Text = "Flat" },
                            new SelectListItem { Value = "Bungalow", Text = "Bungalow" },
                            new SelectListItem { Value = "IndependentHouse", Text = "IndependentHouse" },
                        };
                propertyViewModel.PriceValues = new List<SelectListItem>
                {
                    new SelectListItem { Value = "0" ,Text="--Price--"},
                    new SelectListItem { Value = "1" ,Text="0-10000"},
                    new SelectListItem { Value = "10000" ,Text="10000-20000"},
                    new SelectListItem { Value = "20000" ,Text="20000-30000"},
                    new SelectListItem { Value = "30000" ,Text="Greater than 30000"},
                };
                propertyViewModel.Option = new List<SelectListItem>
                {
                    new SelectListItem { Value = "null" ,Text="--Property Type--"},
                    new SelectListItem { Value = "Sell" ,Text="Sell"},
                    new SelectListItem { Value = "Rent" ,Text="Rent"},
                  
                };

            }

            return View(propertyViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            SellerHouseDetailsViewModel house = null;
            UserDetailsViewModel seller = null;
            SellerDetailsDtoViewModel houseWithSellerDetails = new();


            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var houseDetails = await client.GetAsync($"Buyers/GetHouseDetails/{id}");


                // var houseAndSellerDetails = await client.GetAsync($"Seller/GetSellerDetails/{id}");


                if (houseDetails.IsSuccessStatusCode)
                {

                    house = await houseDetails.Content.ReadAsAsync<SellerHouseDetailsViewModel>();

                    var sellerId = house.UserDetailsId;
                    var sellerDetails = await client.GetAsync($"Seller/GetSellerById/{sellerId}");

                    var cityNameResult = await client.GetAsync($"Cities/GetcityById/{house.CityId}");
                    var cityName = await cityNameResult.Content.ReadAsAsync<CityViewModel>();

                    house.CityName = cityName.CityName;


                    seller = await sellerDetails.Content.ReadAsAsync<UserDetailsViewModel>();

                    //  var result = await houseAndSellerDetails.Content.ReadAsAsync<UserDetailsViewModel>();

                }
                var checkAllImages = await client.GetAsync("HouseImages/GetAllHouseImages");
                if (checkAllImages.IsSuccessStatusCode)
                {
                    var AllImages = await checkAllImages.Content.ReadAsAsync<List<HouseImageViewModel>>();
                    houseWithSellerDetails.HouseImages = AllImages;

                }




                houseWithSellerDetails.HouseDetails = house;
                houseWithSellerDetails.SellerDetails = seller;





                return View(houseWithSellerDetails);
            }

        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int id)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var user = HttpContext.Session.GetString("sellerName");
                var userDetails = await client.GetAsync($"Buyers/GetUserId/{user}");
                if (userDetails.IsSuccessStatusCode)
                {
                    var userDetailsId = await userDetails.Content.ReadAsAsync<BuyerDetailsModel>();
                    BuyerCartModel buyer = new BuyerCartModel
                    {
                        HouseId = id,
                        UserDetaisId = userDetailsId.Id

                    };
                    var res = await client.PostAsJsonAsync("Buyers/AddToCart", buyer);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }

                }
                else
                {
                    return RedirectToAction("Login", "Accounts");
                }


            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Cart(PropertyViewModel propertyView)
        {
            PropertyViewModel propertyViewModel = new();
            List<SellerHouseDetailsViewModel> ho = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);

                var users = HttpContext.Session.GetString("sellerName");
                var userDetails = await client.GetAsync($"Buyers/GetUserId/{users}");
                var userDetailsId = await userDetails.Content.ReadAsAsync<BuyerDetailsModel>();
                var housecheck = await client.GetAsync($"Buyers/GetAllHousesforBuyer");
                var houses = await housecheck.Content.ReadAsAsync<List<SellerHouseDetailsViewModel>>();
                var res = await client.GetAsync($"Buyers/GetMyCart/{userDetailsId.Id}");
                var tempimages = await client.GetAsync("HouseImages/GetAllHouseImages");

                if (res.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    var allImages = await tempimages.Content.ReadAsAsync<List<HouseImage>>();
                    propertyViewModel.HouseImages = allImages;
                    var cartDetails = await res.Content.ReadAsAsync<List<BuyerCartModel>>();



                    propertyViewModel.buyerCartModels = cartDetails;
                    propertyViewModel.HouseViewModels = houses;


                    return View(propertyViewModel);
                }

            }
            propertyViewModel = new PropertyViewModel
            {
                HouseImages = new(),
                HouseViewModels = new(),
                buyerCartModels = new()
            };





            return View(propertyViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFromCart(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var users = HttpContext.Session.GetString("sellerName");

EHS_MVC/Controllers/HomeController.cs
using EHS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EHS_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EHS_MVC/Views/Home/About.cshtml
@{
	ViewData["Title"] = "About";
}
<style>
	.team-single {
		display: block;
		position: relative;
		transition: .3s;
		overflow: hidden;
		padding-right: 1px;
	}

		.team-single img {
			transform: scaleY(1);
			transition: all 0.7s ease-in-out 0s;
		}

		.team-single:hover img {
			transform: scale(1.2);
		}

		.team-single:hover {
			box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
			-webkit-box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
			-moz-box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
			border-radius: 10px;
		}

	.team-overlay {
		background: #ff5f6d none repeat scroll 0 0;
		box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
		-webkit-box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
		-moz-box-shadow: 0 0 30px 0px rgba(0, 0, 0, 0.1);
		padding: 22px 0 12px;
		position: absolute;
		top: 40%;
		transform: translateY(-50%);
		width: 100%;
		opacity: 0;
		visibility: hidden;
		transition: .3s;
	}

	.team-single:hover .team-overlay {
		opacity: 1;
		visibility: visible;
		top: 50%;
	}

	.team-overlay > h5 {
		color: #fff;
		font-weight: 600;
	}

	.team-overlay h6 {
		color: #fff;
	}
</style>
<h1>About</h1>

<section id="team" class="team-area ptb-130">
	<div class="container">
		<div class="row">
			<div class="col-18">
				<div class="section-heading pb-55 text-center">
					<h2 class="mt-4">Team Members</h2>
					<p>We are assigned the Easy housing online Solution Project which have many functionality like The system will allow users to buy, sell, and maintain their property details in a systematic way. The administrator will have complete control over the properties listed on the site and will be responsible for verifying properties added by owners. Owners or sellers can add, edit, and view their properties, and buyers can search, compare, and view property details. </p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-6">
				<div class="team-single">
					<img src="https://i.pinimg.com/originals/2b/de/70/2bde70bb4ec69a8299f05360eb1b56fa.jpg" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Abdul Ahad</h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030850</h6>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="team-single">
					<img src="https://pbs.twimg.com/profile_images/1494127225435684866/X0xWfYyc_400x400.jpg" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Pawan Singh</h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030846</h6>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="team-single">
					<img src="https://wallpapercave.com/wp/wp2377590.jpg" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Srinivas Kurumala</h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030917</h6>
					</div>
				</div>
			</div>
			<br />
			<div class="col-lg-4 col-md-6 mt-4">
				<div class="team-single">
					<img src="https://i.pinimg.com/originals/da/1d/6e/da1d6e70dee30b15e44d906f806c0c96.jpg" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Kishan Kr Yadav</h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030761</h6>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mt-4">
				<div class="team-single">
					<img src="https://cdn.myanimelist.net/images/characters/7/391549.jpg" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Vinay Avala</h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030947</h6>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mt-4">
				<div class="team-single">
					<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFuLom7PPC1zAkeon0aJwRfZF5PSsJVdrOug&usqp=CAU" alt="" height="200" width="200" />
					<div class="team-overlay text-center">
						<h4>Vishva Teja </h4>
						<h5>ASE -ICS VIZAG</h5>
						<h6>E.ID - 1030918</h6>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

EHS_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="banner">
    <div id="banner-text">
        <H1>Easy Housing System</H1>
        <p>Luxury couldn’t come cheaper than this.</p>
        <div>
            <a asp-action="Index" asp-controller="Buyers" class="button"><span>Buy Property</span></a>
            <a asp-action="Login" asp-controller="Accounts"  class="button"> <span>Sell Property</span></a>
        </div>
    </div>
</div>
<div class="last" style="padding-top:50px">
    <a asp-action="About" asp-controller="Home" class="button2" > <span>About Us</span></a>
</div>